Module 1: Review past code
boniface193/admission-trial-revisited pull request #1
Opened 2022-12-05 08:42 UTC by boniface193

### Review past code

HTML
 - html code to be reviewed

CSS
 - css code reviewed

2022-12-05 10:11 UTC, boniface193 reviewed
You're so close to completing your project, please consider the review comment below to make some necessary adjustments

thanks

2022-12-05 10:11 UTC, boniface193 commented on css/style.css
> +  background-color: greenyellow;
linter was not  included, I will suggest you should add linter to your projects as it will allow you to catch syntax errors and help your code to be clean

2022-12-05 10:11 UTC, boniface193 commented on index.html
> +  <div class="container">
you can use semantic HTML tags "like section" for your container instead of a DIV, it will help you stick to the HTML 5 best practice

2022-12-05 10:11 UTC, boniface193 commented on index.html
> +        </p>
In your `<form>`, on each and every `div` tag that contains `class="form-group"`, you can make the tag an HTML 5 semantic tag `<aside>`  instead of a `div` tag 😺  i.e `<aside class="form-group">...</aside> ` in other to stick with the best practice,

2022-12-05 10:11 UTC, boniface193 commented on index.html
> +          Courses</label>
consider adding all `<label>` tags to a  `<section>` tag 

**example**  
```
<section>
  <label>...</label> 
  <label>...</label> 
  <label>...</label> 
</section> 
```
it will make your code look cleaner 😸

2022-12-05 10:35 UTC, jerryowusu requested changes
Hi @boniface193 , 

Good job so far!
Your project is looking fantastic so far :star_struck: 

However, there are few changes you need to make in order to move on to the next level :sunglasses:

![almost there](https://user-images.githubusercontent.com/65233860/205616266-8ce9902f-1897-4989-ade9-f02b6e40c2da.gif)


## Highlights
Used github inline comment feature :heavy_check_mark: 
Communicated in a polite manner :heavy_check_mark: 

## Required Changes ♻️

- [ ] Some of the reviews are not clear enough, hence will confuse :confused:  the student the more. Kindly consider making all your reviews clearer to help the student understand exactly what you are requesting them to do :smile: 


_Check the comments under the review._

## Optional suggestions

- [ ] You can consider adding pictures/emojis/icons to your reviews both inline and summary to make your reviews have a human-friendly appeal. :skull: 

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-12-05 10:35 UTC, jerryowusu commented on index.html
> +        </p>
I am struggling to understand this review. :confused:   Could you please make it more clearer? :pray:
You can also consider adding pictures/emojis to make your reviews have a more human-friendly. :wink:

2022-12-05 10:35 UTC, jerryowusu commented on index.html
> +          Courses</label>
It is difficult to understand what you are trying to communicate and will make the student more confused.  :confused: Could you please make it more clearer? pray
You can also consider adding pictures/emojis to make your reviews have a more human-friendly. :wink:

2022-12-05 16:50 UTC, boniface193 reviewed
Hi, 

Your project is fantastic so far ❤️

please consider the few comments

2022-12-06 08:04 UTC, joskalenda commented on index.html
> +        </p>
You have done a few modifications, at least we can understand the requirement, but I would suggest you explain why the student should consider your changes.

2022-12-06 08:06 UTC, joskalenda commented on index.html
> +          Courses</label>
same as here, let me guess am the student, and someone just says, remove this and add that, indeed I will ask why he wants me to do it, I need to understand the reason before I modify what I have done.

2022-12-06 08:08 UTC, joskalenda approved these changes
| STATUS: APPROVED ✅ |
|------------------------|
| Hi @boniface193 , 🥰|
| Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: Congratulations! 🎉  |
| <img src="https://media2.giphy.com/media/2NpKgBuUZtXpu/giphy.gif"/> |

### Highlights
✅ ...Great use of the inline comment

---------
### Optional suggestions

> _Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

### Cheers and Happy coding!👏👏👏
-------
> Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me(@joskalenda) in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-12-06 08:11 UTC, merged